spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/risk-management-project?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: WojiaGuoguo626
logging:
  level:
    com.itheima: debug
  pattern:
    dateformat: HH:mm:ss
mybatis-plus:
  type-aliases-package: gang.lu.riskmanagementproject.domain.po
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted

  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
  type-enums-package: gang.lu.riskmanagementproject.domain.enums


knife4j:
  enable: true
  openapi:
    title: 路港风险管理系统接口文档
    description: "路港风险管理系统接口文档"
    concat: Franz.Liszt
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - gang.lu.riskmanagementproject.controller