spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/risk-management-project?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: WojiaGuoguo626
  page:
    default-num: 1
    default-size: 10
    max-size: 100
logging:
  level:
    com.itheima: debug
  pattern:
    dateformat: HH:mm:ss
mybatis-plus:
  type-aliases-package: gang.lu.riskmanagementproject.domain.po
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      # 全局更新策略：null 值字段不更新到数据库
      update-strategy: not_null
      # 插入策略：null 值字段不插入
      insert-strategy: not_null

  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package: gang.lu.riskmanagementproject.domain.enums


knife4j:
  enable: true
  openapi:
    title: 路港风险管理系统接口文档
    description: "路港风险管理系统接口文档"
    concat: Franz.Liszt
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - gang.lu.riskmanagementproject.controller

medical:
  min-fatigue-percent: 0.0
  max-fatigue-percent: 100.0
  min-heart-rate: 1
  max-heart-rate: 300
  min-respiratory-rate: 1
  max-respiratory-rate: 60